### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by campbellhealy** [arschles/vectyshortener#1]
I have found my VS code set up after cloning the repo and opening that folder has a lot of dependency issues. I had to clone labstack into src and then I got even more issues.

`C:\Users\User\go\src\vectyshortener>go run .
..\github.com\labstack\echo\middleware\jwt.go:9:2: cannot find package "github.com/dgrijalva/jwt-go" in any of:
        c:\go\src\github.com\dgrijalva\jwt-go (from $GOROOT)
        C:\Users\User\go\src\github.com\dgrijalva\jwt-go (from $GOPATH)
..\github.com\labstack\echo\middleware\body_limit.go:9:2: cannot find package "github.com/labstack/gommon/bytes" in any of:
        c:\go\src\github.com\labstack\gommon\bytes (from $GOROOT)
        C:\Users\User\go\src\github.com\labstack\gommon\bytes (from $GOPATH)
..\github.com\labstack\echo\echo.go:58:2: cannot find package "github.com/labstack/gommon/color" in any of:
        c:\go\src\github.com\labstack\gommon\color (from $GOROOT)
        C:\Users\User\go\src\github.com\labstack\gommon\color (from $GOPATH)
..\github.com\labstack\echo\echo.go:59:2: cannot find package "github.com/labstack/gommon/log" in any of:
        c:\go\src\github.com\labstack\gommon\log (from $GOROOT)
        C:\Users\User\go\src\github.com\labstack\gommon\log (from $GOPATH)
..\github.com\labstack\echo\middleware\csrf.go:11:2: cannot find package "github.com/labstack/gommon/random" in any of:
        c:\go\src\github.com\labstack\gommon\random (from $GOROOT)
        C:\Users\User\go\src\github.com\labstack\gommon\random (from $GOPATH)
..\github.com\labstack\echo\middleware\logger.go:14:2: cannot find package "github.com/valyala/fasttemplate" in any of:
        c:\go\src\github.com\valyala\fasttemplate (from $GOROOT)
        C:\Users\User\go\src\github.com\valyala\fasttemplate (from $GOPATH)
..\github.com\labstack\echo\echo.go:60:2: cannot find package "golang.org/x/crypto/acme" in any of:
        c:\go\src\golang.org\x\crypto\acme (from $GOROOT)
        C:\Users\User\go\src\golang.org\x\crypto\acme (from $GOPATH)
..\github.com\labstack\echo\echo.go:61:2: cannot find package "golang.org/x/crypto/acme/autocert" in any of:
        c:\go\src\golang.org\x\crypto\acme\autocert (from $GOROOT)
        C:\Users\User\go\src\golang.org\x\crypto\acme\autocert (from $GOPATH)`

As you see I am on Windows and was wondering if this was giving me this little hiccup.

**Comment by campbellhealy** [comment]
It's getting dealt with.. woo hoo

**Comment by arschles** [comment]
@vchealy did you find out what was going on? Sorry I didn't get back to you on this sooner.
